namespace HIP.Web.Security;

/// <summary>
/// Marks endpoint sets generated by framework builders whose user-facing Razor routes are inventoried separately.
/// </summary>
/// <remarks>
/// The authorization coverage guard inspects every runtime route by default. Only the static-assets and Razor-components
/// builders receive these explicit markers so an application endpoint cannot escape the guard by choosing a new prefix.
/// </remarks>
public sealed class HipFrameworkGeneratedEndpointMetadata
{
    private HipFrameworkGeneratedEndpointMetadata(string source)
    {
        Source = source;
    }

    /// <summary>Gets the framework endpoint-set source used in diagnostics.</summary>
    public string Source { get; }

    /// <summary>Gets the marker attached only to endpoints produced by <c>MapStaticAssets</c>.</summary>
    public static HipFrameworkGeneratedEndpointMetadata StaticAssets { get; } = new("StaticAssets");

    /// <summary>Gets the marker attached only to endpoints produced by <c>MapRazorComponents</c>.</summary>
    public static HipFrameworkGeneratedEndpointMetadata RazorComponents { get; } = new("RazorComponents");
}
