launch=gsqlite3
gsqlite3-database=/var/lib/powerdns/pdns.sqlite3
gsqlite3-dnssec=yes

local-address=0.0.0.0
local-port=5300
receiver-threads=2
reuseport=yes

api=yes
webserver=yes
webserver-address=0.0.0.0
webserver-port=8081
webserver-allow-from=127.0.0.1,172.16.0.0/12
webserver-loglevel=none
webserver-print-arguments=no
include-dir=/run/pdns

allow-axfr-ips=
allow-dnsupdate-from=
disable-axfr=yes
default-api-rectify=yes
default-soa-content=ns1.guardwithhip.com. hostmaster.guardwithhip.com. 0 10800 3600 604800 300
default-soa-edit=INCEPTION-INCREMENT
default-soa-edit-signed=INCEPTION-INCREMENT
version-string=anonymous
log-dns-details=no
log-dns-queries=no
loglevel=4
