// <auto-generated />
using System;
using HIP.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HIP.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HipDbContext))]
    partial class HipDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HIP.Infrastructure.Persistence.Entities.HipBrowserScanResultEntity", b =>
                {
                    b.Property<string>("ScanResultId")
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DangerousLinksFound")
                        .HasColumnType("integer");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)");

                    b.Property<DateTimeOffset>("LastCheckedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LinksScanned")
                        .HasColumnType("integer");

                    b.Property<string>("PageUrlHash")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<string>("PluginVersion")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("PrivacySafeMetadataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReasonsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecommendedAction")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("RiskyLinksFound")
                        .HasColumnType("integer");

                    b.Property<string>("ScanSource")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("StoredPageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("SuspiciousLinksFound")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ScanResultId");

                    b.HasIndex("Domain");

                    b.HasIndex("LastCheckedUtc");

                    b.HasIndex("RiskLevel");

                    b.HasIndex("Status");

                    b.HasIndex("Domain", "LastCheckedUtc");

                    b.ToTable("hip_browser_scan_results", (string)null);
                });

            modelBuilder.Entity("HIP.Infrastructure.Persistence.Entities.HipDashboardScanAggregateEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Dangerous")
                        .HasColumnType("integer");

                    b.Property<int>("HighRisk")
                        .HasColumnType("integer");

                    b.Property<int>("LimitedTrustData")
                        .HasColumnType("integer");

                    b.Property<int>("MostlyTrusted")
                        .HasColumnType("integer");

                    b.Property<int>("ScansToday")
                        .HasColumnType("integer");

                    b.Property<int>("Suspicious")
                        .HasColumnType("integer");

                    b.Property<int>("TotalScans")
                        .HasColumnType("integer");

                    b.Property<int>("Trusted")
                        .HasColumnType("integer");

                    b.Property<int>("Unknown")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("hip_dashboard_scan_aggregates", (string)null);
                });

            modelBuilder.Entity("HIP.Infrastructure.Persistence.Entities.HipTrustReceiptEntity", b =>
                {
                    b.Property<string>("ReceiptId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("EvaluatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvidenceDigest")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("character varying(71)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IssuerId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProtocolVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ReceiptDigest")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("character varying(71)");

                    b.Property<string>("ReceiptJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RelatedEvaluationId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RuleSetVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SourceEvaluationDigest")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("character varying(71)");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("ReceiptId");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("IssuerId");

                    b.HasIndex("RelatedEvaluationId")
                        .IsUnique();

                    b.HasIndex("SubjectId");

                    b.ToTable("hip_trust_receipts", (string)null);
                });

            modelBuilder.Entity("HIP.Infrastructure.Persistence.HipDbRecord", b =>
                {
                    b.Property<string>("Partition")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Id")
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<long>("AggregateVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Partition", "Id");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("hip_records", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
