namespace HIP.Sdk.Models;

/// <summary>
/// Response contract returned by the HIP status endpoint.
/// </summary>
/// <param name="ServiceName">Logical service name emitted by the API.</param>
/// <param name="AssemblyVersion">Build/version identifier for the running service binary.</param>
/// <param name="UtcTimestamp">UTC timestamp generated by the service at response time.</param>
public sealed record StatusResponse(string ServiceName, string AssemblyVersion, DateTimeOffset UtcTimestamp);
