server:
    interface: 0.0.0.0
    port: 5353
    username: ""
    directory: "/var/lib/unbound"
    chroot: ""
    pidfile: "/tmp/unbound.pid"
    auto-trust-anchor-file: "/var/lib/unbound/root.key"
    module-config: "validator iterator"

    access-control: 0.0.0.0/0 refuse
    access-control: 10.0.0.0/8 allow
    access-control: 172.16.0.0/12 allow
    access-control: 192.168.0.0/16 allow

    do-ip4: yes
    do-ip6: yes
    do-udp: yes
    do-tcp: yes
    hide-identity: yes
    hide-version: yes
    harden-dnssec-stripped: yes
    harden-glue: yes
    harden-referral-path: yes
    qname-minimisation: yes
    aggressive-nsec: yes
    prefetch: yes
    prefetch-key: yes
    deny-any: yes
    minimal-responses: yes
    harden-algo-downgrade: yes
    harden-below-nxdomain: yes
    harden-large-queries: yes
    harden-short-bufsize: yes
    serve-expired: yes
    serve-expired-client-timeout: 1800
    serve-expired-ttl: 86400
    serve-expired-reply-ttl: 30
    so-sndbuf: 0
    so-reuseport: yes
    ede: yes
    val-log-level: 2

    num-threads: 2
    extended-statistics: yes
    statistics-cumulative: yes
    statistics-inhibit-zero: yes
    msg-cache-size: 32m
    msg-cache-slabs: 2
    rrset-cache-size: 64m
    rrset-cache-slabs: 2
    key-cache-size: 16m
    key-cache-slabs: 2
    neg-cache-size: 4m
    cache-min-ttl: 0
    cache-max-ttl: 86400
    cache-max-negative-ttl: 3600

    ratelimit: 1000
    ratelimit-size: 4m
    ratelimit-slabs: 2
    ratelimit-factor: 10
    ratelimit-backoff: yes
    ip-ratelimit: 500
    ip-ratelimit-cookie: 1000
    ip-ratelimit-size: 4m
    ip-ratelimit-slabs: 2
    ip-ratelimit-factor: 10
    ip-ratelimit-backoff: yes

remote-control:
    control-enable: yes
    control-interface: 127.0.0.1
    control-use-cert: no
